name = "Fatherless Spooky Modpack"
author = "Veonise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19022b3aea706916f05917dc48e1c46a83a227062a8f2eb90a92de8a59b7b3c8"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
